# Generated by Django 5.0.4 on 2024-04-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('ready', 'ready'), ('en_cours_execution', 'en_cours_execution'), ('finish', 'finish'), ('probleme', 'probleme')], default='ready', max_length=20)),
                ('importance', models.CharField(choices=[('urgence', 'urgence'), ('not_urgence', 'not_urgence'), ('moderate', 'moderate')], default='not_urgence', max_length=20)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.chef')),
                ('employes', models.ManyToManyField(related_name='tasks', to='users.employe', verbose_name='Employés associés')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
            },
        ),
    ]
