# Generated by Django 5.0.4 on 2024-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='tache',
            name='importance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
