# Generated by Django 5.0.4 on 2024-04-26 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tache_duration_alter_tache_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
