# Generated by Django 5.0.4 on 2024-04-26 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tache_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('audio', models.FileField(upload_to='audios/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.tache')),
            ],
            options={
                'verbose_name': 'Réponse de tâche',
                'verbose_name_plural': 'Réponses de tâches',
            },
        ),
    ]
