# Generated by Django 5.0.4 on 2024-04-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employe_rank_alter_taskresponse_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='specialty',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
