# Generated by Django 5.0.4 on 2024-04-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_employe_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='speciality',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
