# Generated by Django 5.0.4 on 2024-04-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tache_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.chef'),
        ),
    ]
