# Generated by Django 5.0.4 on 2024-04-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employe_specialty'),
        ('users', '0009_tache_speciality'),
    ]

    operations = [
    ]
